// <auto-generated />
namespace POSB.VRF.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatevrftable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatevrftable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811150902564_update-vrf-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
